version: '3.4'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - conf/bigdata.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 50070:50070
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - conf/bigdata.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    depends_on:
      - namenode
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
  spark-master:
    image: bde2020/spark-master:2.2.0-hadoop2.7
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
    ports:
      - 8080:8080
      - 7077:7077
    depends_on:
      - namenode
    env_file:
      - conf/bigdata.env
  spark-worker:
    image: bde2020/spark-worker:2.2.0-hadoop2.7
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083
    env_file:
      - conf/bigdata.env
  spark-notebook:
    image: quay.io/comp-bio-aging/notebook:latest
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    env_file:
      - conf/bigdata.env
    ports:
      #- 9001:9001
      - 9000:9000
    volumes:
      - ./notebooks:/opt/spark-notebook/notebooks
      - ./conf/notebook/repos/m2/repository:/root/.m2/repository
    depends_on:
      - spark-master
      - namenode
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
  # HUE STUFF
  hue:
    image: gethue/hue:latest
    depends_on:
      - namenode
    ports:
      - 8888:8888
    volumes:
      - ./conf/hue/hue.ini:/hue/desktop/conf/pseudo-distributed.ini
    deploy:
        replicas: 1
        mode: replicated
        restart_policy:
          condition: on-failure

volumes:
  datanode:
  namenode:

networks:
  default:
    driver: overlay
    attachable: true
