listen:
  host: 0.0.0.0
  port: 8192

repositories:
  - maven:
      base: http://central.maven.org/maven2/
  - maven:
      base: http://oss.sonatype.org/content/repositories/snapshots
      changing: true
  - maven:
      base: https://jitpack.io
      changing: true


spark:
  properties:
    master: "http://spark:7070[12]"
    spark.driver.memory: 28g
    spark.executor.memory: 60g